SET DEFINE OFF;

-- Fix broken Korean MENU_NAME (wrong UNISTR code points for 검·리·경·체 etc.)
UPDATE HIS_MENU SET MENU_NAME = UNISTR('\C601\C0C1\AC80\C0AC') WHERE MENU_CODE = 'MEDICAL_SUPPORT_IMAGING';
UPDATE HIS_MENU SET MENU_NAME = UNISTR('\AC80\CCB4\AC80\C0AC') WHERE MENU_CODE = 'MEDICAL_SUPPORT_SPECIMEN';
UPDATE HIS_MENU SET MENU_NAME = UNISTR('\BCD1\B9AC\AC80\C0AC') WHERE MENU_CODE = 'MEDICAL_SUPPORT_PATHOLOGY';
UPDATE HIS_MENU SET MENU_NAME = UNISTR('\B0B4\C2DC\ACBD') WHERE MENU_CODE = 'MEDICAL_SUPPORT_ENDOSCOPY';
UPDATE HIS_MENU SET MENU_NAME = UNISTR('\C0DD\B9AC\AE30\B2A5\AC80\C0AC') WHERE MENU_CODE = 'MEDICAL_SUPPORT_PHYSIO';

COMMIT;
EXIT;
