-- STAFF 목록 API는 STAFF_STATUS = 'ACTIVE' 인 행만 조회합니다.
-- DBeaver에서 HOSPITAL.STAFF 데이터는 있지만 화면에 0건이면 아래를 실행하세요.
-- Example:
--   sqlplus hospital/1111@192.168.1.128:1521/XE "@database/oracle/fix_staff_status.sql"

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE HOSPITAL.STAFF ADD (STAFF_STATUS VARCHAR2(10) DEFAULT ''ACTIVE'')';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

UPDATE HOSPITAL.STAFF
   SET STAFF_STATUS = 'ACTIVE'
 WHERE STAFF_STATUS IS NULL
    OR TRIM(STAFF_STATUS) = '';

COMMIT;

SELECT STAFF_ID, STAFF_NAME, STAFF_STATUS
  FROM HOSPITAL.STAFF
 ORDER BY STAFF_ID;

EXIT;
