SET DEFINE OFF;

-- HIS Common Domain (Oracle)
-- Logical entities: USER, ROLE, USER_ROLE, MENU, MENU_ROLE
-- Physical tables use HIS_ prefix to avoid reserved-word conflicts.
-- Run as hp user after user/tablespace provisioning.

BEGIN EXECUTE IMMEDIATE 'DROP TABLE HIS_MENU_ROLE CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE HIS_USER_ROLE CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE HIS_MENU CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE HIS_ROLE CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE HIS_USER CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/

BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_HIS_MENU_ROLE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_HIS_USER_ROLE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_HIS_MENU'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_HIS_ROLE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_HIS_USER'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END;
/

CREATE TABLE HIS_USER (
    USER_ID        NUMBER(19)      NOT NULL,
    USER_CODE      VARCHAR2(40)    NOT NULL,
    USER_NAME      VARCHAR2(100)   NOT NULL,
    EMAIL          VARCHAR2(150),
    USE_YN         CHAR(1)         DEFAULT 'Y' NOT NULL,
    CREATED_AT     TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT     TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_HIS_USER PRIMARY KEY (USER_ID),
    CONSTRAINT UK_HIS_USER_CODE UNIQUE (USER_CODE),
    CONSTRAINT CK_HIS_USER_USE_YN CHECK (USE_YN IN ('Y', 'N'))
);

CREATE SEQUENCE SEQ_HIS_USER START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE HIS_ROLE (
    ROLE_ID         NUMBER(19)      NOT NULL,
    ROLE_CODE       VARCHAR2(40)    NOT NULL,
    ROLE_NAME       VARCHAR2(100)   NOT NULL,
    ROLE_NAME_EN    VARCHAR2(100),
    ROLE_DESC       VARCHAR2(300),
    ROLE_DESC_EN    VARCHAR2(300),
    USE_YN          CHAR(1)         DEFAULT 'Y' NOT NULL,
    CREATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_HIS_ROLE PRIMARY KEY (ROLE_ID),
    CONSTRAINT UK_HIS_ROLE_CODE UNIQUE (ROLE_CODE),
    CONSTRAINT CK_HIS_ROLE_USE_YN CHECK (USE_YN IN ('Y', 'N'))
);

CREATE SEQUENCE SEQ_HIS_ROLE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE HIS_MENU (
    MENU_ID          NUMBER(19)      NOT NULL,
    PARENT_MENU_ID   NUMBER(19),
    MENU_CODE        VARCHAR2(60)    NOT NULL,
    MENU_NAME        VARCHAR2(120)   NOT NULL,
    MENU_NAME_EN     VARCHAR2(120),
    MENU_PATH        VARCHAR2(255),
    MENU_ICON        VARCHAR2(80),
    SORT_ORDER       NUMBER(10)      DEFAULT 0 NOT NULL,
    DEPTH_LEVEL      NUMBER(3)       DEFAULT 0 NOT NULL,
    USE_YN           CHAR(1)         DEFAULT 'Y' NOT NULL,
    CREATED_AT       TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT       TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_HIS_MENU PRIMARY KEY (MENU_ID),
    CONSTRAINT UK_HIS_MENU_CODE UNIQUE (MENU_CODE),
    CONSTRAINT FK_HIS_MENU_PARENT FOREIGN KEY (PARENT_MENU_ID)
        REFERENCES HIS_MENU (MENU_ID) ON DELETE SET NULL,
    CONSTRAINT CK_HIS_MENU_USE_YN CHECK (USE_YN IN ('Y', 'N'))
);

CREATE INDEX IDX_HIS_MENU_PARENT ON HIS_MENU (PARENT_MENU_ID);
CREATE SEQUENCE SEQ_HIS_MENU START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE HIS_USER_ROLE (
    USER_ROLE_ID     NUMBER(19)     NOT NULL,
    USER_ID          NUMBER(19)     NOT NULL,
    ROLE_ID          NUMBER(19)     NOT NULL,
    ASSIGNED_AT      TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    ASSIGNED_BY      VARCHAR2(40),
    CONSTRAINT PK_HIS_USER_ROLE PRIMARY KEY (USER_ROLE_ID),
    CONSTRAINT FK_HIS_USER_ROLE_USER FOREIGN KEY (USER_ID)
        REFERENCES HIS_USER (USER_ID),
    CONSTRAINT FK_HIS_USER_ROLE_ROLE FOREIGN KEY (ROLE_ID)
        REFERENCES HIS_ROLE (ROLE_ID),
    CONSTRAINT UK_HIS_USER_ROLE UNIQUE (USER_ID, ROLE_ID)
);

CREATE INDEX IDX_HIS_USER_ROLE_USER ON HIS_USER_ROLE (USER_ID);
CREATE INDEX IDX_HIS_USER_ROLE_ROLE ON HIS_USER_ROLE (ROLE_ID);
CREATE SEQUENCE SEQ_HIS_USER_ROLE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE HIS_MENU_ROLE (
    MENU_ROLE_ID      NUMBER(19)     NOT NULL,
    MENU_ID           NUMBER(19)     NOT NULL,
    ROLE_ID           NUMBER(19)     NOT NULL,
    PERMIT_READ_YN    CHAR(1)        DEFAULT 'Y' NOT NULL,
    PERMIT_WRITE_YN   CHAR(1)        DEFAULT 'N' NOT NULL,
    PERMIT_DELETE_YN  CHAR(1)        DEFAULT 'N' NOT NULL,
    CONSTRAINT PK_HIS_MENU_ROLE PRIMARY KEY (MENU_ROLE_ID),
    CONSTRAINT FK_HIS_MENU_ROLE_MENU FOREIGN KEY (MENU_ID)
        REFERENCES HIS_MENU (MENU_ID),
    CONSTRAINT FK_HIS_MENU_ROLE_ROLE FOREIGN KEY (ROLE_ID)
        REFERENCES HIS_ROLE (ROLE_ID),
    CONSTRAINT UK_HIS_MENU_ROLE UNIQUE (MENU_ID, ROLE_ID),
    CONSTRAINT CK_HIS_MR_READ CHECK (PERMIT_READ_YN IN ('Y', 'N')),
    CONSTRAINT CK_HIS_MR_WRITE CHECK (PERMIT_WRITE_YN IN ('Y', 'N')),
    CONSTRAINT CK_HIS_MR_DELETE CHECK (PERMIT_DELETE_YN IN ('Y', 'N'))
);

CREATE INDEX IDX_HIS_MENU_ROLE_MENU ON HIS_MENU_ROLE (MENU_ID);
CREATE INDEX IDX_HIS_MENU_ROLE_ROLE ON HIS_MENU_ROLE (ROLE_ID);
CREATE SEQUENCE SEQ_HIS_MENU_ROLE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- Dummy Data (ASCII literals for SQL*Plus charset stability)
INSERT INTO HIS_USER (USER_ID, USER_CODE, USER_NAME, EMAIL, USE_YN)
VALUES (SEQ_HIS_USER.NEXTVAL, 'U1001', 'NURSE_KIM', 'nurse1@hospital.local', 'Y');
INSERT INTO HIS_USER (USER_ID, USER_CODE, USER_NAME, EMAIL, USE_YN)
VALUES (SEQ_HIS_USER.NEXTVAL, 'U1002', 'ADMIN_LEE', 'admin1@hospital.local', 'Y');
INSERT INTO HIS_USER (USER_ID, USER_CODE, USER_NAME, EMAIL, USE_YN)
VALUES (SEQ_HIS_USER.NEXTVAL, 'U1003', 'DOCTOR_PARK', 'doctor1@hospital.local', 'Y');

INSERT INTO HIS_ROLE (ROLE_ID, ROLE_CODE, ROLE_NAME, ROLE_NAME_EN, ROLE_DESC, ROLE_DESC_EN, USE_YN)
VALUES (SEQ_HIS_ROLE.NEXTVAL, 'ROLE_ADMIN', UNISTR('\C2DC\C2A4\D15C \AD00\B9AC\C790'), 'SYSTEM_ADMIN', UNISTR('\ACF5\D1B5 \BA54\B274 \C804\CCB4 \AD8C\D55C'), 'COMMON_MENU_ALL_ACCESS', 'Y');
INSERT INTO HIS_ROLE (ROLE_ID, ROLE_CODE, ROLE_NAME, ROLE_NAME_EN, ROLE_DESC, ROLE_DESC_EN, USE_YN)
VALUES (SEQ_HIS_ROLE.NEXTVAL, 'ROLE_NURSE', UNISTR('\AC04\D638\C0AC'), 'NURSE', UNISTR('\C9C4\B8CC \C9C0\C6D0 \D654\BA74 \AD8C\D55C'), 'CLINIC_SUPPORT_SCREEN_ACCESS', 'Y');
INSERT INTO HIS_ROLE (ROLE_ID, ROLE_CODE, ROLE_NAME, ROLE_NAME_EN, ROLE_DESC, ROLE_DESC_EN, USE_YN)
VALUES (SEQ_HIS_ROLE.NEXTVAL, 'ROLE_DOCTOR', UNISTR('\C758\C0AC'), 'DOCTOR', UNISTR('\C758\C0AC \C804\C6A9 \D654\BA74 \AD8C\D55C'), 'DOCTOR_ONLY_SCREEN_ACCESS', 'Y');

INSERT INTO HIS_MENU (MENU_ID, PARENT_MENU_ID, MENU_CODE, MENU_NAME, MENU_PATH, MENU_ICON, SORT_ORDER, DEPTH_LEVEL, USE_YN)
VALUES (SEQ_HIS_MENU.NEXTVAL, NULL, 'DASHBOARD', 'Dashboard', '/dashboard', 'Home', 1, 0, 'Y');
INSERT INTO HIS_MENU (MENU_ID, PARENT_MENU_ID, MENU_CODE, MENU_NAME, MENU_PATH, MENU_ICON, SORT_ORDER, DEPTH_LEVEL, USE_YN)
VALUES (SEQ_HIS_MENU.NEXTVAL, NULL, 'PATIENT', 'Patient', NULL, 'People', 2, 0, 'Y');
INSERT INTO HIS_MENU (MENU_ID, PARENT_MENU_ID, MENU_CODE, MENU_NAME, MENU_PATH, MENU_ICON, SORT_ORDER, DEPTH_LEVEL, USE_YN)
VALUES (SEQ_HIS_MENU.NEXTVAL, 2, 'PATIENT_LIST', 'PatientList', '/patients', NULL, 1, 1, 'Y');

INSERT INTO HIS_USER_ROLE (USER_ROLE_ID, USER_ID, ROLE_ID, ASSIGNED_BY)
VALUES (SEQ_HIS_USER_ROLE.NEXTVAL, 1, 1, 'SYSTEM');
INSERT INTO HIS_USER_ROLE (USER_ROLE_ID, USER_ID, ROLE_ID, ASSIGNED_BY)
VALUES (SEQ_HIS_USER_ROLE.NEXTVAL, 2, 2, 'SYSTEM');
INSERT INTO HIS_USER_ROLE (USER_ROLE_ID, USER_ID, ROLE_ID, ASSIGNED_BY)
VALUES (SEQ_HIS_USER_ROLE.NEXTVAL, 3, 3, 'SYSTEM');

INSERT INTO HIS_MENU_ROLE (MENU_ROLE_ID, MENU_ID, ROLE_ID, PERMIT_READ_YN, PERMIT_WRITE_YN, PERMIT_DELETE_YN)
VALUES (SEQ_HIS_MENU_ROLE.NEXTVAL, 1, 1, 'Y', 'Y', 'Y');
INSERT INTO HIS_MENU_ROLE (MENU_ROLE_ID, MENU_ID, ROLE_ID, PERMIT_READ_YN, PERMIT_WRITE_YN, PERMIT_DELETE_YN)
VALUES (SEQ_HIS_MENU_ROLE.NEXTVAL, 2, 2, 'Y', 'N', 'N');
INSERT INTO HIS_MENU_ROLE (MENU_ROLE_ID, MENU_ID, ROLE_ID, PERMIT_READ_YN, PERMIT_WRITE_YN, PERMIT_DELETE_YN)
VALUES (SEQ_HIS_MENU_ROLE.NEXTVAL, 3, 3, 'Y', 'Y', 'N');

COMMIT;
EXIT;
