-- Run this script as SYSDBA
-- Example:
-- sqlplus "/ as sysdba" "@database/oracle/prepare_hp_user.sql"

ALTER USER hp IDENTIFIED BY "7777" ACCOUNT UNLOCK;
ALTER USER hp DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP;
ALTER USER hp QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW TO hp;
EXIT;
