SET HEADING OFF;
SET FEEDBACK OFF;
SET PAGESIZE 0;
SET VERIFY OFF;

SELECT 'HIS_USER=' || COUNT(*) FROM HIS_USER;
SELECT 'HIS_ROLE=' || COUNT(*) FROM HIS_ROLE;
SELECT 'HIS_MENU=' || COUNT(*) FROM HIS_MENU;
SELECT 'HIS_USER_ROLE=' || COUNT(*) FROM HIS_USER_ROLE;
SELECT 'HIS_MENU_ROLE=' || COUNT(*) FROM HIS_MENU_ROLE;
EXIT;
