SET HEADING OFF;
SET FEEDBACK OFF;
SET PAGESIZE 0;
SET VERIFY OFF;

SELECT 'CLINICAL_CNT=' || COUNT(*) FROM HIS_MENU WHERE MENU_CODE LIKE 'CLINICAL%';
SELECT 'SUPPORT_CNT=' || COUNT(*) FROM HIS_MENU WHERE MENU_CODE LIKE 'MEDICAL_SUPPORT%';

SELECT MENU_CODE || ':' || MENU_NAME || ':' || NVL(MENU_NAME_EN, 'NULL')
  FROM HIS_MENU
 WHERE MENU_CODE IN ('CLINICAL', 'MEDICAL_SUPPORT', 'CLINICAL_LIST', 'MEDICAL_SUPPORT_RECORD')
 ORDER BY MENU_ID;

EXIT;
